# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoAe37ouYJEopmmoX-5Q0V-hTczjhec9
"""

import os
import subprocess

# Full path to your single FASTA file (update this to your actual file path)
input_fasta = "path_to_your_input_fasta_file"

# Full path to your output directory (update this to your actual output directory path)
output_dir = "path_to_your_output_directory"

# Ensure the output directory exists
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Generate the output file name based on the input FASTA file name
output_file = os.path.join(output_dir, f"{os.path.splitext(os.path.basename(input_fasta))[0]}_prodigal.gbk")

# Command to run Prodigal
command = [
    "prodigal",
    "-i", input_fasta,
    "-o", output_file,
    "-c",
    "-m",
    "-g", "11",
    "-p", "meta"
]

# Run the command and capture the output
result = subprocess.run(command, capture_output=True, text=True)

# Print the results
print(f"Running Prodigal on {os.path.basename(input_fasta)}")
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)

print("Prodigal processing complete.")
